###
### tox.ini with parts taken from the sagemath source
###
[tox]
envlist = doctest, coverage, relint, codespell, ruff, pytest
skipsdist = true

[testenv]
setenv =
    SAGE=sage
    HOME={toxinidir}
allowlist_externals =
    {env:SAGE}
    tox
    pytest

commands = tox -c {toxinidir}/tox.ini -e {envname} -- {posargs}

[testenv:pytest]
commands = pytest -s

[testenv:doctest]
description =
   run Sage the Sage doctester (same as "sage -t")
commands =
    {env:SAGE} -t --warn-long 15 -p 0 {posargs:{toxinidir}/src/}

[testenv:coverage]
description =
    give information about doctest coverage of files
    (same as "sage --coverage[all]")
commands =
    {env:SAGE} --coverage {posargs:{toxinidir}/src/}

[testenv:relint]
description =
    check whether some forbidden patterns appear
    (includes all patchbot pattern-exclusion plugins)
# https://github.com/codingjoe/relint
# The patterns are in .relint.yaml
deps = relint
allowlist_externals = find
commands = find {posargs:{toxinidir}/src/} -exec relint -c {toxinidir}/.relint.yaml \{\} +

[testenv:codespell]
description =
    check for misspelled words in source code
deps = codespell
commands = codespell \
    --skip="*.so,*.c,*.cpp,.git,.idea,.ipynb_checkpoints,.tox,dist,*.egg-info,*.html" \
    --dictionary=- \
    {posargs:{toxinidir}/src}


[testenv:ruff]
allowlist_externals = ruff
commands =
    ruff check .
    ruff format .


