"""
Class for spaces of Hilbert Maass forms.
"""

import logging
from typing import Any, ParamSpec

from hilbert_modgroup.all import HilbertModularGroup
from hilbert_modgroup.hilbert_modular_group_class import HilbertModularGroup_class
from hilbert_modgroup.pullback import HilbertPullback
from numpy import linspace
from sage.matrix.constructor import matrix
from sage.misc.cachefunc import cached_method
from sage.modules.free_module_element import vector
from sage.modules.module import Module
from sage.rings.complex_mpfr import ComplexField, ComplexNumber
from sage.rings.number_field.number_field_base import NumberField as NumberFieldBase
from sage.rings.number_field.number_field_ideal import NumberFieldFractionalIdeal
from sage.rings.real_mpfr import RealNumber as RealNumber_class
from sage.structure.element import ModuleElement

from .hilbert_maass_element import HilbertMaassForm_Element
from .utils import (
    Integer_t,
    Real_t,
    dual_ideal,
    ideal_generator,
    number_field_from_json,
    number_field_to_json,
)

P = ParamSpec("P")
log = logging.getLogger(__name__)

# Suppress debug output from hilbert_modular_group which hard-codes
# logger.setLevel(DEBUG) in hilbert_modular_group_class.py
logging.getLogger("hilbert_modgroup.hilbert_modular_group_class").setLevel(logging.WARNING)


class HilbertMaassFormSpace(Module):
    Element = HilbertMaassForm_Element

    def __init__(
        self, group: HilbertModularGroup_class | NumberFieldBase | Integer_t, **kwargs: P.kwargs
    ) -> None:
        r"""
        Initialize a Hilbert Maass form space.

        INPUT:

        - ``group`` -- HilbertModularGroup_class or NumberFieldBase
        - ``cuspidal`` -- bool (optional)

        EXAMPLES::

            sage: from maass_forms_hilbert.all import HilbertMaassFormSpace
            ...
            sage: H = HilbertMaassFormSpace(QuadraticField(2), cuspidal=False)
        """
        if not isinstance(group, HilbertModularGroup_class):
            group = HilbertModularGroup(group)
        self._group = group
        self._cuspidal = kwargs.pop("cuspidal", False)
        self._number_field = group.base_ring().number_field()
        different = self._number_field.different()
        representatives = self.group().ideal_cusp_representatives()
        self._dual_ideals = [ideal**-1 * different**-1 for ideal in representatives]
        self._pullback = None
        self._dual_ideal_basis_matrix = []
        super().__init__(group.base_ring(), **kwargs)

    def an_element(self):
        """
        Return a sample element of the Hilbert Maass form space.

        EXAMPLES::

            sage: from maass_forms_hilbert.all import HilbertMaassFormSpace
            sage: H = HilbertMaassFormSpace(QuadraticField(2), cuspidal=False)
            sage: f = H.an_element()
            sage: f.parent() == H
            True
            sage: f.spectral_parameter()
            (0.000000000000000, 0.000000000000000)
        """
        from .hilbert_maass_element import HilbertMaassForm

        spectral_parameter = (ComplexField(53)(0, 0),) * self.number_field().degree()
        return HilbertMaassForm(self, spectral_parameter=spectral_parameter)

    def to_json(self):
        """
        JSON representation of self.

        EXAMPLES::

            sage: from maass_forms_hilbert.all import HilbertMaassFormSpace
            sage: H = HilbertMaassFormSpace(QuadraticField(2), cuspidal=False)
            sage: H.to_json()
            {'cuspidal': False, 'number_field': {'names': ['a'], 'polynomial': 'x^2 - 2'}}

        """
        return {
            "number_field": number_field_to_json(self.number_field()),
            "cuspidal": self._cuspidal,
        }

    @classmethod
    def from_json(cls, data):
        """
        Create an instance of self from JSON data.

        EXAMPLES::

            sage: from maass_forms_hilbert.all import HilbertMaassFormSpace
            sage: H = HilbertMaassFormSpace(QuadraticField(2), cuspidal=False)
            sage: H.from_json(H.to_json()) == H
            True

        """
        nf = number_field_from_json(data["number_field"])
        group = HilbertModularGroup(nf)
        return cls(group, cuspidal=data["cuspidal"])

    def __repr__(self):
        r"""
        Return string representation of self.

        OUTPUT:

        - string

        EXAMPLES::

            sage: from maass_forms_hilbert.all import HilbertMaassFormSpace
            sage: H = HilbertMaassFormSpace(QuadraticField(2), cuspidal=False)
            sage: repr(H) # +NORMALIZE_WHITESPACE
            'HilbertMaassFormSpace(Hilbert Modular Group PSL(2) over Maximal Order generated by a
                in Number Field in a with defining polynomial x^2 - 2 with a = 1.414213562373095?)'
            sage: H  # +NORMALIZE_WHITESPACE
            HilbertMaassFormSpace(Hilbert Modular Group PSL(2) over Maximal Order generated by a
                in Number Field in a with defining polynomial x^2 - 2 with a = 1.414213562373095?)
        """
        return f"HilbertMaassFormSpace({self.group()})"

    def __hash__(self):
        r"""
        Return a hash value for self.

        OUTPUT:

        - integer hash value

        EXAMPLES::

            sage: from maass_forms_hilbert.all import HilbertMaassFormSpace
            sage: H = HilbertMaassFormSpace(QuadraticField(2), cuspidal=False)
            sage: hash(H) == hash(H)  # hash is consistent
            True
            sage: H2 = HilbertMaassFormSpace(QuadraticField(2), cuspidal=False)
            sage: hash(H) == hash(H2)  # equal objects have equal hashes
            True
        """
        return hash(str(self.to_json()))

    def __eq__(self, other: Any) -> bool:
        """
        Is self equal to other.

        Note: Isomorphic number fields (e.g. QuadraticField(2) and NumberField(x^2-2)
              have equal level, so we use the level for comparison of groups.

        INPUT:

        - `other` -- object to compare self with

        EXAMPLES::

            sage: from maass_forms_hilbert.all import HilbertMaassFormSpace
            sage: H1 = HilbertMaassFormSpace(QuadraticField(2), cuspidal=False)
            sage: H1 == H1
            True
            sage: H1 != H1
            False
            sage: H2 = HilbertMaassFormSpace(NumberField(x^2-2, names='a'), cuspidal=False)
            sage: H1 == H2
            True
            sage: H1 != H2
            False
            sage: H3 = HilbertMaassFormSpace(NumberField(x^2-2, names='a'), cuspidal=True)
            sage: H1 == H3
            False
            sage: H1 != H3
            True


        """
        if not isinstance(other, HilbertMaassFormSpace):
            return False
        if self.is_cuspidal() != other.is_cuspidal():
            return False
        # Need to check isomorphic fields
        if not self.number_field().is_isomorphic(other.number_field()):
            return False
        this_level = self.group().level()
        other_level_gens = other.group().level().gens_reduced()
        return self.number_field().fractional_ideal(other_level_gens) == this_level

    def group(self):
        """
        The group of self.

        EXAMPLES::

            sage: from maass_forms_hilbert.all import HilbertMaassFormSpace
            sage: H = HilbertMaassFormSpace(QuadraticField(2), cuspidal=False)
            sage: H.group()
            Hilbert Modular Group PSL(2) over Maximal Order generated by a in Number Field in a ...

        """
        return self._group

    def number_field(self):
        """
        The group of self.

        EXAMPLES::

            sage: from maass_forms_hilbert.all import HilbertMaassFormSpace
            sage: H = HilbertMaassFormSpace(QuadraticField(2), cuspidal=False)
            sage: H.number_field()
            Number Field in a with defining polynomial x^2 - 2 with a = 1.414213562373095?
            sage: H.number_field() == H.group().base_ring().number_field()
            True

        """

        return self._number_field

    def dual_ideals(self):
        r"""
        Return the dual ideals for this space.

        The dual ideals are computed as $\mathfrak{a}^{-1}\mathcal{D}^{-1}$ where $\mathcal{D}$
        is the different ideal and $\mathfrak{a}$ runs through the cusp representatives.

        OUTPUT:

        - list of dual ideals

        EXAMPLES::

            sage: from maass_forms_hilbert.all import HilbertMaassFormSpace
            sage: H = HilbertMaassFormSpace(QuadraticField(2), cuspidal=False)
            sage: duals = H.dual_ideals()
            sage: all(d * H.number_field().different() * H.group().ideal_cusp_representatives()[i] == H.number_field().ideal(1)
            ....:     for i, d in enumerate(duals))
            True
        """
        return self._dual_ideals

    @cached_method
    def dual_ideal_basis_matrix(self, ideal: NumberFieldFractionalIdeal | Integer_t = None):
        r"""
        Return the basis matrix for the dual ideal.

        This method returns a matrix whose rows are the complex embeddings of the integral
        basis elements of the dual ideal.

        INPUT:

        - ``ideal`` -- NumberFieldFractionalIdeal or integer (optional); if an integer is given,
          it is used as an index into the list of dual ideals

        OUTPUT:

        - matrix; basis matrix for the dual ideal

        EXAMPLES::

            sage: from maass_forms_hilbert.all import HilbertMaassFormSpace
            sage: H = HilbertMaassFormSpace(QuadraticField(2), cuspidal=False)
            sage: M = H.dual_ideal_basis_matrix()
            sage: M.nrows() == H.number_field().degree()
            True
            sage: M.ncols() == H.number_field().degree()
            True
            sage: M = H.dual_ideal_basis_matrix(0)  # same as default
            sage: M.parent()
            Full MatrixSpace of 2 by 2 dense matrices over Real Field with 53 bits of precision
        """
        if ideal is None:
            ideal = 0
        if isinstance(ideal, NumberFieldFractionalIdeal):
            ideal = self._dual_ideals.index(ideal)
        if not self._dual_ideal_basis_matrix:
            self._dual_ideal_basis_matrix = [
                matrix(self.pullback()._get_lattice_and_ideal_basis(dual_ideal)[0])
                for dual_ideal in self.dual_ideals()
            ]
        return self._dual_ideal_basis_matrix[ideal]

    @cached_method
    def dual_ideal_element(
        self,
        coordinates: tuple[Integer_t] | ModuleElement,
        ideal: NumberFieldFractionalIdeal | Integer_t = None,
    ):
        r"""
        Return the element in the dual ideal corresponding to coordinates.

        This method computes an element in the dual ideal by taking the linear combination
        of basis elements with the given coordinates.

        INPUT:

        - ``coordinates`` -- tuple or ModuleElement; coefficients with respect to the dual ideal basis
        - ``ideal`` -- NumberFieldFractionalIdeal or integer (optional); specifies which dual ideal to use

        OUTPUT:

        - vector; complex embeddings of the element in the dual ideal

        EXAMPLES::

            sage: from maass_forms_hilbert.all import HilbertMaassFormSpace
            sage: H = HilbertMaassFormSpace(QuadraticField(2), cuspidal=False)
            sage: v = H.dual_ideal_element((1, 0))
            sage: v.parent()
            Vector space of dimension 2 over Real Field with 53 bits of precision
            sage: H.dual_ideal_element((1, 1)) == H.dual_ideal_basis_matrix() * vector([1, 1])
            True
        """
        return self.dual_ideal_basis_matrix(ideal) * vector(coordinates)

    def dual_ideal_pos_generator(self, ideala: NumberFieldFractionalIdeal = None):
        r"""
        Return the positive generator of the dual ideal.

        INPUT:

        - ``ideala`` -- (default: None) fractional ideal; if None, uses the first ideal cusp representative

        OUTPUT:

        - The positive generator of the dual ideal

        EXAMPLES::

            sage: from maass_forms_hilbert.all import HilbertMaassFormSpace
            sage: H = HilbertMaassFormSpace(QuadraticField(2), cuspidal=False)
            sage: gen = H.dual_ideal_pos_generator()
            sage: gen in H.number_field()
            True
        """
        if not ideala:
            ideala = self.group().ideal_cusp_representatives()[0]
        ideala_dual = dual_ideal(ideala)
        return ideal_generator(ideala_dual)

    def is_cuspidal(self):
        """
        Is self cuspidal

        EXAMPLES::

            sage: from maass_forms_hilbert.all import HilbertMaassFormSpace
            sage: H = HilbertMaassFormSpace(QuadraticField(2), cuspidal=False)
            sage: H.is_cuspidal()
            False
            sage: H = HilbertMaassFormSpace(QuadraticField(2), cuspidal=True)
            sage: H.is_cuspidal()
            True

        """
        return self._cuspidal

    def pullback(self):
        """
        An instance of HilbertPullback on the group of self.

        EXAMPLES::

            sage: from maass_forms_hilbert.all import HilbertMaassFormSpace
            sage: H = HilbertMaassFormSpace(QuadraticField(2), cuspidal=False)
            sage: H.pullback()
            Pullback class for Hilbert Modular Group PSL(2) over Maximal Order generated by a ...

        """
        if not self._pullback:
            self._pullback = HilbertPullback(self.group())
        return self._pullback

    def _element_constructor_(
        self,
        s: tuple | HilbertMaassForm_Element = None,
        check: bool = False,
        **kwargs: P.kwargs,
    ):
        r"""
        Construct an element of this Hilbert Maass form space.

        This is an internal method used for coercion and element construction.

        INPUT:

        - ``s`` -- tuple or HilbertMaassForm_Element; spectral parameter or existing element
        - ``check`` -- bool (default: False); whether to validate inputs
        - ``**kwargs`` -- additional keyword arguments passed to element constructor

        OUTPUT:

        - HilbertMaassForm_Element

        EXAMPLES::

            sage: from maass_forms_hilbert.all import HilbertMaassFormSpace
            sage: H = HilbertMaassFormSpace(QuadraticField(2), cuspidal=False)
            sage: f = H._element_constructor_((0.5, 0.5))
            sage: f.parent() == H
            True
            sage: H._element_constructor_(f) is f  # coercion of existing element
            True
            sage: g = H._element_constructor_(0.5, check=True)  # scalar gets repeated
            sage: g.spectral_parameter()
            (0.500000000000000, 0.500000000000000)
        """
        if isinstance(s, self.element_class):
            # Only return x if the parent *is* self to avoid coercion problems.
            if s.parent() is self:
                return s
            if check and s.parent() != self:
                raise ValueError(f"Can not construct an element of {self} from {s}")
            raise NotImplementedError("Coercion of Hilbert--Maass forms is not implemented")
        if check and isinstance(s, (RealNumber_class, ComplexNumber, int, float)):
            s = [s] * self._number_field.degree()
        return self.element_class(self, s, **kwargs)

    def check_interval(
        self,
        r_start: Real_t,
        r_stop: Real_t,
        fixed_params: tuple[Real_t] = None,
        nsteps: int = 10,
        Y1: Real_t = None,
        Y2: Real_t = None,
        M: tuple[int] = None,
        ideala: NumberFieldFractionalIdeal = None,
        coeff: tuple = None,
    ) -> list:
        r"""
        Check the interval for sign changes in the functional.

        This method computes Fourier coefficients at different points in the interval
        and looks for sign changes in the difference between coefficients computed
        with different Y parameters.

        INPUT:

        - ``r_start`` -- real; start of interval
        - ``r_stop`` -- real; end of interval
        - ``fixed_params`` -- tuple of reals (optional); fixed spectral parameters
        - ``nsteps`` -- int (default: 10); number of points to check
        - ``Y1``, ``Y2`` -- real values (optional); Y parameters for coefficient computation
        - ``M`` -- tuple of ints (optional); bounds for coefficient indices
        - ``ideala`` -- NumberFieldFractionalIdeal (optional); ideal to use
        - ``coeff`` -- tuple (optional); which coefficient to check

        OUTPUT:

        - list of tuples (s, C1, C2) where s is the spectral parameter and C1, C2 are
          the computed coefficients at Y1 and Y2 respectively

        EXAMPLES::

            sage: from maass_forms_hilbert.all import HilbertMaassFormSpace
            sage: from sage.rings.real_mpfr import RealField
            sage: H = HilbertMaassFormSpace(QuadraticField(2), cuspidal=False)
            sage: RF = RealField(53)
            sage: res = H.check_interval(RF(0), RF(1), nsteps=3) # long time
            sage: len(res) == 3  # three points checked # long time
            True
            sage: all(len(s) == H.number_field().degree() for s, C1, C2 in res)  # long time
            True
        """
        G = self.an_element()
        CF = ComplexField(r_start.parent().prec())
        ideala = ideala or self._number_field.fractional_ideal(1)
        Y1v = Y1 or (0.75, 0.75)
        Y2v = Y2 or (0.73, 0.73)
        M = M or ((-4, 4),) * 2
        result = []
        f0 = 0
        f1 = 0
        r_previous = r_start
        for r in linspace(r_start, r_stop, nsteps):
            if fixed_params is None:
                s = (CF(0.5, r),) * len(M)
            else:
                # Replace fixed params = None by the variable r
                rs = [r0 or r for r0 in fixed_params]
                s = tuple(CF(0.5, r0) for r0 in rs)
            log.debug(f"r = {r}, s = {s}")
            G._spectral_parameter = s
            C1 = G.compute_coefficients(s, ideala, ideala, M=M, Y=Y1v)
            C2 = G.compute_coefficients(s, ideala, ideala, M=M, Y=Y2v)
            result.append((s, C1, C2))
            coeff = coeff or (0, 1)
            f0 = self.functional(C1, C2, coeff=coeff)
            if f0 * f1 < 0 and max(abs(f0), abs(f1)) < 1e-2:
                log.info(f"Sign change {coeff} in interval: [{r_previous}, {r}]")
            f0 = self.functional(C1, C2)
            r_previous = r
            f1 = f0
        return result

    def functional(self, C1, C2, coeff=(0, 1)):
        r"""
        Compute the difference of real parts of coefficients.

        This method is used in interval checking to detect sign changes between
        coefficients computed with different parameters.

        INPUT:

        - ``C1``, ``C2`` -- HilbertMaassCoefficients; coefficient objects to compare
        - ``coeff`` -- tuple (default: (0, 1)); which coefficient to compare

        OUTPUT:

        - real number; difference between real parts of the specified coefficients

        EXAMPLES::

            sage: from maass_forms_hilbert.all import HilbertMaassFormSpace
            sage: from maass_forms_hilbert.modform.coefficients import HilbertMaassCoefficients
            sage: H = HilbertMaassFormSpace(QuadraticField(2), cuspidal=False)
            sage: M = ((-1, 1),) * 2
            sage: c = matrix([[0],[1],[2],[3],[4],[5],[6],[7],[8]])
            sage: C1 = HilbertMaassCoefficients(c, M ,[(1+1j,1+1j)], H)
            sage: C2 = HilbertMaassCoefficients(c, M ,[(1+1j,1+1j)], H)
            sage: H.functional(C1, C2, (0,1))  # difference of real parts
            0
        """
        return C1[coeff].real() - C2[coeff].real()
