[pytest]
testpaths =
    tests
addopts =
    -s
;    --cov=src
;    --cov-append
;    --cov-report=term-missing
;    --log-cli-level=ERROR
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
	ignore::UserWarning
doctest_optionflags = NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL
python_files = test_*.py
pythonpath = ./src
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
